FROM node:12

WORKDIR /usr/src/app

COPY package*.json ./

COPY . .

RUN npm install --no-optional && npm cache clean  --force

ENV PATH /usr/src/node_modules/.bin:$PATH

EXPOSE 8080

CMD ["npm", "run", "serve"]