version: "3.9"
services:
  database:
    image: mysql
    restart: always
    env_file:
      - ./dev.env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./dbinit:/docker-entrypoint-initdb.d
    ports:
      - 5555:3306
  backend:
    build: ./backend
    env_file:
      - ./dev.env
    volumes:
      - ./backend:/usr/src/app
  # client:
  #   build: ./client
  #   env_file:
  #     - ./dev.env
  #   volumes:
  #     - ./client:/usr/src/app
  #   ports:
  #     - 8080:8080
