FROM node:12

WORKDIR /usr/src/app

COPY . .

RUN npm install --no-optional && npm cache clean  --force

ENV PATH /usr/src/node_modules/.bin:$PATH


ENTRYPOINT [ "/usr/src/app/entrypoint.sh" ]

EXPOSE 8080

CMD ["npm", "start"]